apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    run: frontapp-service
spec: 
  selector:
    app: todo-ui
    
  ports: 
    - name: http
      port: 8081
      targetPort: 80
      protocol: TCP
  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  name: back-service
  labels:
    run: backapp-service
spec: 
  selector:
    app: todo-api
  ports: 
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort

