apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec: 
  storageClassName: mylocalstorage
  accesModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 20Gi

--- 
#how do you want it implemented ??
apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: local-storage 
spec: 
  storageClassName: mylocalstorage
  capacity: 
    storage: 20Gi
  accesModes: 
    - ReadWriteOnce 
  hostPath: 
    path: "/mnt/data"
    type: DirectoryOrCreate 
---
#service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000
  selector:
    app: mongodb
  type: NodePort